
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('crops').del()
    .then(function () {
      // Inserts seed entries
      return knex('crops').insert([
        {
          description: 'Lemons',
          details: 'Lemon tree',
          garden_description: 'Lemon Tree, right corner',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$2',
          crop_status: 1,
          owner_id: 1,
          plant_id: 1,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2019-04-30T15:51:53.723',
          selling: false,
        },
        {
          description: 'Blueberries',
          details: 'Lowbush',
          garden_description: `Oliver's blueberry bush`,
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$2',
          crop_status: 1,
          owner_id: 1,
          plant_id: 2,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2019-04-30T15:51:53.723',
          selling: false,
        },
        {
          description: 'Cherries',
          details: 'Sour cherries.',
          garden_description: 'To be sold',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$4',
          crop_status: 1,
          owner_id: 1,
          plant_id: 3,
          harvest_date: '2018-09-12T15:51:53.723',
          watering_date: '2018-09-09T00:48:38.382Z',
          selling: true,
        },
        {
          description: 'Apples',
          details: 'Apples for sale or trade, would love some fruits!',
          garden_description: 'For stand',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$4',
          crop_status: 1,
          owner_id: 2,
          plant_id: 4,
          harvest_date: '2018-09-12T15:51:53.723',
          watering_date: '2018-09-09T00:48:38.382Z',
          selling: true,
        },
        {
          description: 'Strawberries',
          details: 'In season now! Sweet and super!',
          garden_description: 'Strawberry bush',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$4',
          crop_status: 1,
          owner_id: 3,
          plant_id: 5,
          harvest_date: '2018-09-12T15:51:53.723',
          watering_date: '2018-09-09T00:48:38.382Z',
          selling: true,
        },
        {
          description: 'Apples',
          details: 'fuji apples',
          garden_description: 'fuji apples',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$3',
          crop_status: 1,
          owner_id: 3,
          plant_id: 4,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2018-09-11T15:51:53.723',
          selling: true,
        },
        {
          description: 'eggplants',
          details: 'Giving away, just message me',
          garden_description: '',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$3',
          crop_status: 1,
          owner_id: 3,
          plant_id: 6,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2018-09-11T15:51:53.723',
          selling: true,
        },
        {
          description: 'tomatoes',
          details: 'cherry tomatoes',
          garden_description: 'cherry tomato',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$3',
          crop_status: 1,
          owner_id: 4,
          plant_id: 8,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2018-09-11T15:51:53.723',
          selling: true,
        },
        {
          description: 'green apples',
          details: 'granny smith apples',
          garden_description: '',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$3',
          crop_status: 1,
          owner_id: 2,
          plant_id: 5,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2018-09-11T15:51:53.723',
          selling: true,
        },
        {
          description: 'dark cherries',
          details: 'go really well with drinks, lots of batches to sell',
          garden_description: 'for sale',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$3',
          crop_status: 1,
          owner_id: 6,
          plant_id: 3,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2018-09-11T15:51:53.723',
          selling: false,
        },
        {
          description: 'Mint',
          details: 'lots and lots of mint, these grow so quickly!',
          garden_description: '',
          planted_on: null,
          watering_interval: 7,
          inventory: 0,
          price: '$5',
          crop_status: 1,
          owner_id: 5,
          plant_id: 16,
          watering_date: '2018-09-09T00:48:38.382Z',
          harvest_date: '2019-01-30T15:51:53.723',
          selling: true,
        }
      ]);
    });
};
